BINNAME := strategytest
BINEXT := so

# directories
SRCDIR := src
BINDIR := ../../../bin/linux
OBJDIR := ../../../temp/linux/$(BINNAME)
DEPDIR := ../../../temp/linux/$(BINNAME)

CFLAGS := -std=c17
CXXFLAGS := -std=c++20
CPPFLAGS := -Wall -Wextra -fPIC
LDFLAGS := -shared -rdynamic
LDLIBS :=

CC := gcc
CXX := g++
LD := $(CXX)

include ../Makefile.in